### ISSUE TITLE
Add documentation on Kyverno Policies

### ISSUE THREAD

**Issue by glrf** [appuio/component-appuio-cloud#51]
## Context
As part of this component we introduced more and more kyverno policies. Some of these policies are quite complex and some are triggered by other policies.

We should add documentation on all policies and especially how they interact with each other. What I would like to have:

* Brief documentation on each policy (Might be able to auto-generate these)
* Description on some of the workflows. e.g.:
  * Namespace creation (What is checked, what is generated ..)
  * Project creation (How does the project template and kyverno policy interact)
  * Namespace quotas

**Comment by tobru** [comment]
There are some policies documented on the upstream documentation of Kyverno: https://kyverno.io/policies/. It looks like they have a custom renderer for that: https://github.com/kyverno/website/tree/main/render. This might help for inspiration.
